USE CompAccInc_DWRam;

INSERT INTO [CompAccInc_DWRam]..CUSTOMER_DIM (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_ADDRESS, WEBSITE, CREDIT_LIMIT)
SELECT CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_ADDRESS, WEBSITE, CREDIT_LIMIT
FROM [CompAccInc_OLTPRam]..CUSTOMERS;

INSERT INTO [CompAccInc_DWRam]..EMPLOYEE_DIM (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, HIRE_DATE, MANAGER_ID, JOB_TITLE)
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, HIRE_DATE, MANAGER_ID, JOB_TITLE
FROM [CompAccInc_OLTPRam]..EMPLOYEES;

INSERT INTO [CompAccInc_DWRam]..PRODUCT_DIM 
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, STANDARD_COST, LIST_PRICE, CATEGORY_NAME, STOCK)
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRODUCT_DESCRIPTION, P.STANDARD_COST, P.LIST_PRICE, PC.CATEGORY_NAME, Inv.Qty
FROM (SELECT Product_ID, SUM(Quantity) as Qty FROM [CompAccInc_OLTPRam]..INVENTORIES GROUP BY Product_ID) Inv
RIGHT JOIN [CompAccInc_OLTPRam]..PRODUCTS P ON Inv.PRODUCT_ID = P.PRODUCT_ID
JOIN [CompAccInc_OLTPRam]..PRODUCT_CATEGORIES PC ON P.CATEGORY_ID = PC.CATEGORY_ID


INSERT INTO [CompAccInc_DWRam]..ORDERS_DIM (ORDER_ID, ORDER_STATUS, ORDER_DATE, ITEM_ID)
SELECT O.ORDER_ID, O.ORDER_STATUS, O.ORDER_DATE, OI.ITEM_ID
FROM [CompAccInc_OLTPRam]..ORDER_ITEMS OI
JOIN [CompAccInc_OLTPRam]..ORDERS O ON OI.ORDER_ID = O.ORDER_ID;

DECLARE @StartDate DATETIME = '20130601' 
DECLARE @EndDate DATETIME = '20230717' 
DECLARE @curDate DATE
DECLARE @FirstDayMonth DATE
DECLARE @QtrMonthNo INT
DECLARE @FirstDayQtr DATE
SET @curdate = @StartDate
WHILE @curDate < @EndDate 
BEGIN
    SET @FirstDayMonth = DATEFROMPARTS(YEAR(@curDate), MONTH(@curDate), 1)
    SET @QtrMonthNo = ((DATEPART(QUARTER, @CurDate) - 1) * 3) + 1 
    SET @FirstDayQtr = DATEFROMPARTS(YEAR(@curDate), @QtrMonthNo, 1)
    INSERT INTO TIME_DIM
    SELECT 
        FORMAT(@curDate, 'yyyy-MM-dd') AS TIME_ID,
        DATEPART(YEAR, @curDate) AS TIME_YEAR,
        DATEPART(QUARTER, @curDate) AS TIME_QUARTER,
        DATEPART(MONTH, @curDate) AS TIME_MONTH,
        DATEPART(WEEK, @curDate) AS TIME_WEEK,
        DATEPART(DAY, @curDate) AS TIME_DATE,
        DATEPART(WEEKDAY, @curDate) AS TIME_DAY
    SET @curDate = DATEADD(DAY, 1, @curDate)
END

INSERT INTO SALES_FACT (ORDER_KEY, CUSTOMER_KEY, PRODUCT_KEY, EMPLOYEE_KEY, TIME_KEY, QUANTITY, UNIT_PRICE)
SELECT
    OD.ORDER_KEY,
    C.CUSTOMER_KEY,
    P.PRODUCT_KEY,
    E.EMPLOYEE_KEY,
    T.TIME_KEY,
    OI.QUANTITY,
    OI.UNIT_PRICE
FROM
    [CompAccInc_OLTPRam]..ORDER_ITEMS OI
    JOIN [CompAccInc_OLTPRam]..ORDERS O ON OI.ORDER_ID = O.ORDER_ID
    JOIN [CompAccInc_DWRam]..ORDERS_DIM OD ON OI.ORDER_ID = OD.ORDER_ID AND OI.ITEM_ID = OD.ITEM_ID
    JOIN [CompAccInc_DWRam]..CUSTOMER_DIM C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    JOIN [CompAccInc_DWRam]..PRODUCT_DIM P ON OI.PRODUCT_ID = P.PRODUCT_ID
    JOIN [CompAccInc_DWRam]..EMPLOYEE_DIM E ON O.SALESMAN_ID = E.EMPLOYEE_ID
    JOIN [CompAccInc_DWRam]..TIME_DIM T ON O.ORDER_DATE = CAST(T.TIME_KEY AS DATE);

